apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  # point to thee parent directory of the chart 
  chartHome: ../../
helmCharts:
  - name: sample-chart 
    releaseName: my-app 
    # This refers to the values file inside our chart 
    valuesFile: ../../sample-chart/values.yaml