apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 

helmGlobals:
  chartHome: ../../../
namePrefix: dev-
labels: 
  - pairs: 
      env: development
    includeSelectors: true 
namespace: development 
helmCharts:
  - name: sample-chart 
    releaseName: my-app
    valuesFile: values.yaml 